version: '2'

services:
  manual:
    build: ./
    volumes:
      - ./:/opticskxi/
    working_dir: /opticskxi
    command: make doc.pdf
  vignette:
    build: ./
    volumes:
      - ./:/opticskxi/
    working_dir: /opticskxi
    command: make vignette
  pkg_check:
    build: ./
    volumes:
      - ./:/opticskxi/
    working_dir: /opticskxi/
    command: make
